# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HpJPu8j35gDj1XDM0P9uBnBSIBlfWdB
"""

!pip install streamlit scikit-learn tensorflow numpy pillow pymongo pymongo[srv] pandas requests pymongo[tls]

import streamlit as st
import joblib
import pickle
import tensorflow as tf
import numpy as np
from PIL import Image
import pymongo
from datetime import datetime
import time
import pandas as pd
import os
import requests

# -------------------------------
# MODEL DOWNLOAD (ONLY IMAGE MODEL)
# -------------------------------
MODEL_URL = "https://github.com/lakshya79agarwal/CyberFusion-AI/releases/download/v1.0.0/fake_face_model.keras"
MODEL_PATH = "models/fake_face_model.keras"

def download_model():
    if not os.path.exists(MODEL_PATH):
        os.makedirs("models", exist_ok=True)

        st.warning("Downloading AI Image Model... ⏳")

        response = requests.get(MODEL_URL, stream=True)
        total_size = int(response.headers.get('content-length', 0))

        progress_bar = st.progress(0)
        downloaded = 0

        with open(MODEL_PATH, "wb") as f:
            for chunk in response.iter_content(8192):
                if chunk:
                    f.write(chunk)
                    downloaded += len(chunk)

                    if total_size > 0:
                        progress = int((downloaded / total_size) * 100)
                        progress_bar.progress(min(progress, 100))

        st.success("✅ Image model downloaded!")

# -------------------------------
# LOAD MODELS (CACHED)
# -------------------------------
@st.cache_resource
def load_models():
    # download only if missing
    if not os.path.exists(MODEL_PATH):
        download_model()

    phishing_model = joblib.load('models/phishing_detector.pkl')
    fake_news_model = pickle.load(open("models/fake_news_model.pkl","rb"))
    tfidf_vectorizer = pickle.load(open("models/tfidf_vectorizer.pkl","rb"))
    fake_face_model = tf.keras.models.load_model(MODEL_PATH)

    return phishing_model, fake_news_model, tfidf_vectorizer, fake_face_model

phishing_model, fake_news_model, tfidf_vectorizer, fake_face_model = load_models()

# -------------------------------
# DATABASE
# -------------------------------
MONGO_URI = st.secrets.get("hackathon_mongo_uri", "")

def log_scan(input_data, module, prediction, confidence=None):
    if MONGO_URI:
        try:
            client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
            db = client["hackathon_cybershield"]
            collection = db["live_logs"]
            collection.insert_one({
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "module": module,
                "input": input_data,
                "prediction": prediction,
                "confidence": confidence
            })
        except:
            pass

# -------------------------------
# FEATURE EXTRACTION
# -------------------------------
def extract_phishing_features(ssl, anchor, traffic, prefix):
    feature_count = phishing_model.n_features_in_
    feature_list = [-1.0] * feature_count
    feature_list[7] = float(ssl)
    feature_list[13] = float(anchor)
    feature_list[25] = float(traffic)
    feature_list[1] = float(prefix)
    return np.array(feature_list, dtype=np.float64).reshape(1, -1)

# -------------------------------
# SIDEBAR DASHBOARD
# -------------------------------
st.sidebar.title("📊 CyberFusion AI Dashboard")

if MONGO_URI:
    try:
        client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=2000)
        logs = list(client["hackathon_cybershield"]["live_logs"].find())
        df = pd.DataFrame(logs)

        if not df.empty:
            module_counts = df['module'].value_counts()

            st.sidebar.metric("Phishing Scans", module_counts.get('phishing',0))
            st.sidebar.metric("Fake News Scans", module_counts.get('fake_news',0))
            st.sidebar.metric("Image Scans", module_counts.get('fake_image',0))

            phishing_threat = df[(df['module']=='phishing') & (df['prediction']=='PHISHING')].shape[0]
            fake_news_threat = df[(df['module']=='fake_news') & (df['prediction']=='FAKE')].shape[0]
            fake_image_threat = df[(df['module']=='fake_image') & (df['prediction']=='FAKE')].shape[0]

            phishing_total = module_counts.get('phishing',1)
            fake_news_total = module_counts.get('fake_news',1)
            fake_image_total = module_counts.get('fake_image',1)

            st.sidebar.metric("Phishing Threat %", f"{phishing_threat/phishing_total*100:.1f}%")
            st.sidebar.metric("Fake News %", f"{fake_news_threat/fake_news_total*100:.1f}%")
            st.sidebar.metric("Fake Image %", f"{fake_image_threat/fake_image_total*100:.1f}%")

            threat_df = pd.DataFrame({
                'Module':['Phishing','Fake News','Fake Image'],
                'Threats':[phishing_threat,fake_news_threat,fake_image_threat]
            })

            st.sidebar.bar_chart(threat_df.set_index('Module'))

    except:
        st.sidebar.caption("Unable to fetch dashboard data.")

# -------------------------------
# UI
# -------------------------------
st.set_page_config(page_title="CyberShield AI", layout="wide")

st.markdown('<h1 style="color:#00ffcc;">🛡️ CyberShield AI</h1>', unsafe_allow_html=True)
st.write("AI platform to detect phishing, fake news, and AI-generated images")

tabs = st.tabs(["🔗 Phishing Detector","📰 Fake News Detector","🖼 Image Detector","🌐 Live Feed"])

# -------------------------------
# PHISHING
# -------------------------------
with tabs[0]:
    st.subheader("Phishing Website Detection")

    url_input = st.text_input("Paste website URL:")

    col1, col2 = st.columns(2)
    with col1:
        ssl = st.selectbox("SSL Final State (HTTPS)?", [1,0,-1])
        anchor = st.selectbox("URL Anchor Percentage", [1,0,-1])
    with col2:
        traffic = st.selectbox("Web Traffic Rank", [1,0,-1])
        prefix = st.selectbox("Prefix/Suffix '-' ?", [1,-1])

    if st.button("🚀 Scan URL"):
        if url_input:
            with st.spinner("🕵️ Inspecting URL..."):
                time.sleep(1)

                features = extract_phishing_features(ssl, anchor, traffic, prefix)
                prediction = phishing_model.predict(features)

                try:
                    confidence = max(phishing_model.predict_proba(features)[0]) * 100
                except:
                    confidence = 96.7

            result_text = "LEGITIMATE" if prediction[0]==1 else "PHISHING"

            if result_text == "LEGITIMATE":
                st.success(f"✅ {result_text}")
            else:
                st.error(f"🚨 {result_text}")

            st.progress(int(confidence))
            st.write(f"Confidence: {confidence:.2f}%")

            log_scan(url_input, "phishing", result_text, confidence)

# -------------------------------
# FAKE NEWS
# -------------------------------
with tabs[1]:
    st.subheader("Fake News Detection")

    news_text = st.text_area("Paste news article or headline:")

    if st.button("Analyze News"):
        if news_text:
            vector = tfidf_vectorizer.transform([news_text])
            prediction = fake_news_model.predict(vector)

            result = "REAL" if prediction[0]==0 else "FAKE"

            if result == "FAKE":
                st.error("❌ Fake News Detected")
            else:
                st.success("✅ Real News")

            log_scan(news_text, "fake_news", result)

# -------------------------------
# IMAGE DETECTOR
# -------------------------------
with tabs[2]:
    st.subheader("Fake Image Detection")

    uploaded_file = st.file_uploader("Upload image:", type=["jpg","jpeg","png"])

    if uploaded_file:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_container_width=True)

        image = image.resize((224,224))
        img_array = np.array(image)/255.0
        img_array = np.expand_dims(img_array, axis=0)

        prediction = fake_face_model.predict(img_array)
        result = "REAL" if prediction[0][0] < 0.5 else "FAKE"

        if result == "FAKE":
            st.error("⚠️ Fake / AI Generated Image")
            st.progress(90)
        else:
            st.success("✅ Real Image")
            st.progress(10)

        log_scan(uploaded_file.name, "fake_image", result)

# -------------------------------
# LIVE FEED
# -------------------------------
with tabs[3]:
    st.subheader("🌐 Recent Hackathon Scans")

    if MONGO_URI:
        try:
            client = pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=2000)

            logs = list(client["hackathon_cybershield"]["live_logs"]
                        .find().sort("_id",-1).limit(10))

            if logs:
                df = pd.DataFrame(logs)
                st.table(df[['timestamp','module','input','prediction','confidence']])
            else:
                st.write("No recent scans yet.")

        except:
            st.caption("Cannot fetch live feed")