# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HpJPu8j35gDj1XDM0P9uBnBSIBlfWdB
"""


import streamlit as st
import joblib
import tensorflow as tf
import numpy as np
from PIL import Image
import pymongo
from datetime import datetime
import time
import pandas as pd
import os
import requests
import keras

# -------------------------------
# CONFIG
# -------------------------------
st.set_page_config(page_title="CyberFusion AI", layout="wide")

MODEL_URL = "https://github.com/lakshya79agarwal/CyberFusion-AI/releases/download/v1.0.0/fake_face_model.keras"
MODEL_PATH = "models/fake_face_model.keras"

MONGO_URI = st.secrets.get("hackathon_mongo_uri", "")

# -------------------------------
# DOWNLOAD MODEL
# -------------------------------
def download_model():
    if not os.path.exists(MODEL_PATH):
        os.makedirs("models", exist_ok=True)

        st.warning("Downloading AI Image Model... ⏳")

        response = requests.get(MODEL_URL, stream=True)
        total_size = int(response.headers.get('content-length', 0))

        progress_bar = st.progress(0)
        downloaded = 0

        with open(MODEL_PATH, "wb") as f:
            for chunk in response.iter_content(8192):
                if chunk:
                    f.write(chunk)
                    downloaded += len(chunk)

                    if total_size > 0:
                        progress = int((downloaded / total_size) * 100)
                        progress_bar.progress(min(progress, 100))

        st.success("✅ Image model downloaded!")

# -------------------------------
# LOAD MODELS
# -------------------------------
@st.cache_resource
def load_models():
    try:
        download_model()

        phishing_model = joblib.load('models/phishing_detector (1).pkl')
        fake_news_model = joblib.load('models/fake_news_model.pkl')
        tfidf_vectorizer = joblib.load('models/tfidf_vectorizer.pkl')
        from tensorflow import keras
        
        fake_face_model = keras.models.load_model(MODEL_PATH, compile=False, safe_mode=False)

        return phishing_model, fake_news_model, tfidf_vectorizer, fake_face_model

    except Exception as e:
        st.error(f"Critical Error: {e}")
        st.stop()

# ✅ LOAD MODELS HERE
phishing_model, fake_news_model, tfidf_vectorizer, fake_face_model = load_models()

# -------------------------------
# DATABASE
# -------------------------------
@st.cache_resource
def get_mongodb_client():
    if MONGO_URI:
        return pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
    return None

client = get_mongodb_client()

def log_scan(input_data, module, prediction, confidence=None):
    if client:
        try:
            db = client["hackathon_cybershield"]
            collection = db["live_logs"]
            collection.insert_one({
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "module": module,
                "input": input_data,
                "prediction": prediction,
                "confidence": confidence
            })
        except:
            pass

# -------------------------------
# FEATURE EXTRACTION
# -------------------------------
def extract_phishing_features(model, ssl, anchor, traffic, prefix):
    feature_count = model.n_features_in_
    feature_list = [-1.0] * feature_count

    feature_list[7] = float(ssl)
    feature_list[13] = float(anchor)
    feature_list[25] = float(traffic)
    feature_list[1] = float(prefix)

    return np.array(feature_list, dtype=np.float64).reshape(1, -1)

# -------------------------------
# UI HEADER
# -------------------------------
st.markdown('<h1 style="color:#00ffcc;">🛡️ CyberFusion AI</h1>', unsafe_allow_html=True)
st.write("AI platform to detect phishing, fake news, and AI-generated images")

tabs = st.tabs(["🔗 Phishing Detector","📰 Fake News Detector","🖼 Image Detector","🌐 Live Feed"])

# -------------------------------
# PHISHING
# -------------------------------
with tabs[0]:
    st.subheader("Phishing Website Detection")

    url_input = st.text_input("Paste website URL:")

    col1, col2 = st.columns(2)
    with col1:
        ssl = st.selectbox("SSL Final State (HTTPS)?", [1,0,-1])
        anchor = st.selectbox("URL Anchor Percentage", [1,0,-1])
    with col2:
        traffic = st.selectbox("Web Traffic Rank", [1,0,-1])
        prefix = st.selectbox("Prefix/Suffix '-' ?", [1,-1])

    if st.button("🚀 Scan URL"):
        if url_input:
            with st.spinner("🕵️ Inspecting URL..."):
                time.sleep(1)

                features = extract_phishing_features(phishing_model, ssl, anchor, traffic, prefix)
                prediction = phishing_model.predict(features)

                try:
                    confidence = max(phishing_model.predict_proba(features)[0]) * 100
                except:
                    confidence = 95.0

            result_text = "LEGITIMATE" if prediction[0]==1 else "PHISHING"

            if result_text == "LEGITIMATE":
                st.success(f"✅ {result_text}")
            else:
                st.error(f"🚨 {result_text}")

            st.progress(int(confidence))
            st.write(f"Confidence: {confidence:.2f}%")

            log_scan(url_input, "phishing", result_text, confidence)

# -------------------------------
# FAKE NEWS
# -------------------------------
with tabs[1]:
    st.subheader("Fake News Detection")

    news_text = st.text_area("Paste news article or headline:")

    if st.button("Analyze News"):
        if news_text:
            vector = tfidf_vectorizer.transform([news_text])
            prediction = fake_news_model.predict(vector)

            result = "REAL" if prediction[0]==0 else "FAKE"

            if result == "FAKE":
                st.error("❌ Fake News Detected")
            else:
                st.success("✅ Real News")

            log_scan(news_text, "fake_news", result)

# -------------------------------
# IMAGE DETECTOR
# -------------------------------
with tabs[2]:
    st.subheader("Fake Image Detection")

    uploaded_file = st.file_uploader("Upload image:", type=["jpg","jpeg","png"])

    if uploaded_file:
        image = Image.open(uploaded_file)
        st.image(image, caption="Uploaded Image", use_container_width=True)

        image = image.resize((224,224))
        img_array = np.array(image)/255.0
        img_array = np.expand_dims(img_array, axis=0)

        prediction = fake_face_model.predict(img_array)
        result = "REAL" if prediction[0][0] < 0.5 else "FAKE"

        if result == "FAKE":
            st.error("⚠️ Fake / AI Generated Image")
            st.progress(90)
        else:
            st.success("✅ Real Image")
            st.progress(10)

        log_scan(uploaded_file.name, "fake_image", result)

# -------------------------------
# LIVE FEED
# -------------------------------
with tabs[3]:
    st.subheader("🌐 Recent Scans")

    if MONGO_URI:
        try:
            logs = list(client["hackathon_cybershield"]["live_logs"]
                        .find().sort("_id",-1).limit(10))

            if logs:
                df = pd.DataFrame(logs)
                st.table(df[['timestamp','module','input','prediction','confidence']])
        except:
            st.warning("Could not load live data")
