# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HpJPu8j35gDj1XDM0P9uBnBSIBlfWdB
"""



import streamlit as st
import os
import joblib
import numpy as np
import pandas as pd
from PIL import Image
from datetime import datetime
import pymongo
import tensorflow as tf
import requests

# -------------------------------
# 1. Configuration & Paths
# -------------------------------
st.set_page_config(page_title="CyberFusion AI", layout="wide", page_icon="🛡️")

# UPDATE THIS LINK with your actual GitHub Release URL
MODEL_URL = "https://github.com/lakshya79agarwal/CyberFusion-AI/releases/download/v1.0/model.h5"
IMAGE_MODEL_PATH = "models/fake_face_model.tflite"
os.makedirs("models", exist_ok=True)

# -------------------------------
# 2. MongoDB Setup
# -------------------------------
MONGO_URI = st.secrets.get("hackathon_mongo_uri", "")

@st.cache_resource
def get_mongo_client():
    if MONGO_URI:
        try:
            return pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=2000)
        except:
            return None
    return None

client = get_mongo_client()

def log_scan(input_data, module, prediction, confidence=None):
    if client:
        try:
            db = client["hackathon_cybershield"]
            db["live_logs"].insert_one({
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "module": module,
                "input": str(input_data)[:100],
                "prediction": prediction,
                "confidence": confidence
            })
        except:
            pass

# -------------------------------
# 3. Model Loading Logic
# -------------------------------
@st.cache_resource
def load_all_models():
    # 1. DOWNLOAD LOGIC
    if not os.path.exists(IMAGE_MODEL_PATH):
        with st.spinner("Downloading TFLite model... 🚀"):
            try:
                # Adding headers mimics a browser to prevent GitHub from blocking the request
                headers = {'User-Agent': 'Mozilla/5.0'}
                response = requests.get(MODEL_URL, headers=headers, stream=True)
                
                if response.status_code == 200:
                    with open(IMAGE_MODEL_PATH, "wb") as f:
                        f.write(response.content)
                else:
                    st.error(f"Download Failed! Status: {response.status_code}. Check your Release URL.")
                    st.stop()
            except Exception as e:
                st.error(f"Download Error: {e}")
                st.stop()

    # 2. LOADING LOGIC
    try:
        phish = joblib.load('models/phishing_detector.pkl')
        news = joblib.load('models/fake_news_model.pkl')
        tfidf = joblib.load('models/tfidf_vectorizer.pkl')
        
        # Initialize TFLite
        interpreter = tf.lite.Interpreter(model_path=IMAGE_MODEL_PATH)
        interpreter.allocate_tensors()
        return phish, news, tfidf, interpreter
    except Exception as e:
        # If it still fails here, the file on GitHub itself is broken
        if os.path.exists(IMAGE_MODEL_PATH):
            os.remove(IMAGE_MODEL_PATH) # Delete the broken file so it retries next time
        st.error(f"🔴 Load Error: {e}")
        st.stop()
# Initialize models globally
phishing_model, fake_news_model, tfidf_vectorizer, tflite_interpreter = load_all_models()

# -------------------------------
# 4. Feature Extraction
# -------------------------------
def extract_phishing_features(ssl, anchor, traffic, prefix):
    # Dynamically match the feature count of your specific model
    feature_count = phishing_model.n_features_in_
    features = np.zeros(feature_count).reshape(1, -1)
    
    # Map inputs to your model's specific indices (Adjust if needed)
    features[0, 1] = prefix
    features[0, 7] = ssl
    features[0, 13] = anchor
    features[0, 25] = traffic
    return features

# -------------------------------
# 5. UI Layout
# -------------------------------
st.markdown('<h1 style="color:#00ffcc;">🛡️ CyberFusion AI</h1>', unsafe_allow_html=True)
st.write("Real-time detection platform for Phishing, Fake News, and AI-Generated Content.")

tabs = st.tabs(["🔗 Phishing", "📰 Fake News", "🖼 Image Detector", "🌐 Live Feed"])

# --- TAB 1: PHISHING ---
with tabs[0]:
    st.subheader("Phishing Website Analysis")
    url_input = st.text_input("Enter URL:")
    c1, c2 = st.columns(2)
    with c1:
        ssl_val = st.selectbox("SSL HTTPS Status?", [1, 0, -1])
        anchor_val = st.selectbox("URL Anchor %", [1, 0, -1])
    with c2:
        traffic_val = st.selectbox("Web Traffic Rank", [1, 0, -1])
        prefix_val = st.selectbox("Prefix/Suffix '-'?", [1, -1])

    if st.button("🚀 Run Scan"):
        if url_input:
            feat = extract_phishing_features(ssl_val, anchor_val, traffic_val, prefix_val)
            pred = phishing_model.predict(feat)
            conf = max(phishing_model.predict_proba(feat)[0])*100 if hasattr(phishing_model, "predict_proba") else 95.0
            res = "LEGITIMATE" if pred[0] == 1 else "PHISHING"
            
            if res == "LEGITIMATE":
                st.success(f"✅ Result: {res}")
            else:
                st.error(f"🚨 Result: {res}")
            st.write(f"Confidence: {conf:.2f}%")
            log_scan(url_input, "phishing", res, conf)

# --- TAB 2: FAKE NEWS ---
with tabs[1]:
    st.subheader("NLP News Verification")
    news_input = st.text_area("Paste article text:")
    if st.button("⚖️ Verify"):
        if news_input:
            vec = tfidf_vectorizer.transform([news_input])
            pred = fake_news_model.predict(vec)
            res = "REAL" if pred[0] == 0 else "FAKE"
            if res == "REAL": st.success("✅ Real News")
            else: st.error("❌ Fake News Detected")
            log_scan(news_input[:50], "fake_news", res)

# --- TAB 3: IMAGE DETECTOR ---
with tabs[2]:
    st.subheader("AI Image Forensics")
    up_file = st.file_uploader("Upload Image:", type=["jpg", "png", "jpeg"])
    if up_file:
        img = Image.open(up_file).convert('RGB').resize((128, 128))
        st.image(img, caption="Analysis Image", use_container_width=True)
        
        # TFLite Preprocessing
        arr = np.array(img, dtype=np.float32) / 255.0
        arr = np.expand_dims(arr, axis=0)
        
        in_idx = tflite_interpreter.get_input_details()[0]['index']
        out_idx = tflite_interpreter.get_output_details()[0]['index']
        
        tflite_interpreter.set_tensor(in_idx, arr)
        tflite_interpreter.invoke()
        score = tflite_interpreter.get_tensor(out_idx)[0][0]
        
        res = "REAL" if score < 0.5 else "FAKE"
        if res == "REAL": st.success(f"✅ Real Image (Score: {1-score:.2%})")
        else: st.error(f"⚠️ AI Generated (Score: {score:.2%})")
        log_scan(up_file.name, "fake_image", res, float(score*100))

# --- TAB 4: LIVE FEED ---
with tabs[3]:
    st.subheader("🌐 Recent Scans")
    if client:
        try:
            db = client["hackathon_cybershield"]
            logs = list(db["live_logs"].find().sort("_id", -1).limit(10))
            if logs:
                st.table(pd.DataFrame(logs)[['timestamp', 'module', 'input', 'prediction']])
        except:
            st.info("Connect to MongoDB to see live feed.")
