# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-HpJPu8j35gDj1XDM0P9uBnBSIBlfWdB
"""



import streamlit as st
import os
import requests
import joblib
import numpy as np
import pandas as pd
from PIL import Image
from datetime import datetime
import pymongo
import tensorflow as tf

# -------------------------------
# Page Config
# -------------------------------
st.set_page_config(page_title="CyberFusion AI", layout="wide")
st.markdown('<h1 style="color:#00ffcc;">🛡️ CyberFusion AI</h1>', unsafe_allow_html=True)
st.write("AI platform to detect phishing, fake news, and AI-generated images")

# -------------------------------
# MongoDB (optional)
# -------------------------------
MONGO_URI = st.secrets.get("hackathon_mongo_uri", "")
@st.cache_resource
def get_mongo_client():
    try:
        if MONGO_URI:
            return pymongo.MongoClient(MONGO_URI, serverSelectionTimeoutMS=2000)
    except:
        return None
    return None

client = get_mongo_client()

def log_scan(input_data, module, prediction, confidence=None):
    if client:
        try:
            db = client["hackathon_cybershield"]
            db["live_logs"].insert_one({
                "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                "module": module,
                "input": input_data,
                "prediction": prediction,
                "confidence": confidence
            })
        except:
            pass

# -------------------------------
# Model Download / Load
# -------------------------------
IMAGE_MODEL_URL = "https://drive.google.com/file/d/1u4fA0MhZ8mUpO0KR6T3VeEW3ja2286yW/view?usp=drive_link"
IMAGE_MODEL_PATH = "models/fake_face_model.tflite"
os.makedirs("models", exist_ok=True)

def download_image_model():
    if not os.path.exists(IMAGE_MODEL_PATH):
        st.warning("Downloading AI Image Model... ⏳")
        response = requests.get(IMAGE_MODEL_URL, stream=True)
        with open(IMAGE_MODEL_PATH, "wb") as f:
            f.write(response.content)
        st.success("✅ Image model downloaded!")

download_image_model()

@st.cache_resource
def load_models():
    try:
        phishing_model = joblib.load('models/phishing_detector (1).pkl')
        fake_news_model = joblib.load('models/fake_news_model.pkl')
        tfidf_vectorizer = joblib.load('models/tfidf_vectorizer.pkl')

        # Load TFLite interpreter
        interpreter = tf.lite.Interpreter(model_path=IMAGE_MODEL_PATH)
        interpreter.allocate_tensors()
        return phishing_model, fake_news_model, tfidf_vectorizer, interpreter
    except Exception as e:
        st.error(f"Model loading error: {e}")
        st.stop()

phishing_model, fake_news_model, tfidf_vectorizer, tflite_interpreter = load_models()

# -------------------------------
# Tabs UI
# -------------------------------
tabs = st.tabs(["🔗 Phishing Detector","📰 Fake News Detector","🖼 Image Detector","🌐 Live Feed"])

# -------------------------------
# Phishing Tab
# -------------------------------
with tabs[0]:
    st.subheader("Phishing Website Detection")
    url_input = st.text_input("Paste website URL:")

    col1, col2 = st.columns(2)
    with col1:
        ssl = st.selectbox("SSL Final State (HTTPS)?", [1,0,-1])
        anchor = st.selectbox("URL Anchor Percentage", [1,0,-1])
    with col2:
        traffic = st.selectbox("Web Traffic Rank", [1,0,-1])
        prefix = st.selectbox("Prefix/Suffix '-' ?", [1,-1])

    if st.button("🚀 Scan URL"):
        if url_input:
            features = np.zeros(phishing_model.n_features_in_).reshape(1, -1)
            features[0,1] = prefix
            features[0,7] = ssl
            features[0,13] = anchor
            features[0,25] = traffic

            prediction = phishing_model.predict(features)
            confidence = max(phishing_model.predict_proba(features)[0])*100 if hasattr(phishing_model, "predict_proba") else 95
            result_text = "LEGITIMATE" if prediction[0]==1 else "PHISHING"

            st.success(result_text) if result_text=="LEGITIMATE" else st.error(result_text)
            st.write(f"Confidence: {confidence:.2f}%")
            st.progress(int(confidence))
            log_scan(url_input, "phishing", result_text, confidence)

# -------------------------------
# Fake News Tab
# -------------------------------
with tabs[1]:
    st.subheader("Fake News Detection")
    news_text = st.text_area("Paste news article or headline:")

    if st.button("Analyze News"):
        if news_text:
            vector = tfidf_vectorizer.transform([news_text])
            prediction = fake_news_model.predict(vector)
            result = "REAL" if prediction[0]==0 else "FAKE"
            st.success("✅ Real News") if result=="REAL" else st.error("❌ Fake News Detected")
            log_scan(news_text, "fake_news", result)

# -------------------------------
# Image Detector Tab
# -------------------------------
with tabs[2]:
    st.subheader("Fake Image Detection")
    uploaded_file = st.file_uploader("Upload image:", type=["jpg","jpeg","png"])

    if uploaded_file:
        image = Image.open(uploaded_file).resize((128,128))
        st.image(image, caption="Uploaded Image", use_container_width=True)
        img_array = np.array(image, dtype=np.float32)/255.0
        img_array = np.expand_dims(img_array, axis=0)

        input_details = tflite_interpreter.get_input_details()
        output_details = tflite_interpreter.get_output_details()
        tflite_interpreter.set_tensor(input_details[0]['index'], img_array)
        tflite_interpreter.invoke()
        prediction = tflite_interpreter.get_tensor(output_details[0]['index'])[0][0]

        result = "REAL" if prediction < 0.5 else "FAKE"
        st.success("✅ Real Image") if result=="REAL" else st.error("⚠️ Fake / AI Generated Image")
        st.progress(10 if result=="REAL" else 90)
        log_scan(uploaded_file.name, "fake_image", result)

# -------------------------------
# Live Feed Tab
# -------------------------------
with tabs[3]:
    st.subheader("🌐 Recent Scans")
    if client:
        try:
            logs = list(client["hackathon_cybershield"]["live_logs"].find().sort("_id",-1).limit(10))
            if logs:
                df = pd.DataFrame(logs)
                st.table(df[['timestamp','module','input','prediction','confidence']])
        except:
            st.info("No live logs available.")
